---
- hosts: nodes
  remote_user: root
  gather_facts: false
  become: yes
  become_method: sudo
  
  vars:
    java8_repository: "ppa:openjdk-r/ppa"
    utilities:
      - git
      - nginx
      - openjdk-8-jdk
      - openjdk-8-jre
      - npm
      - maven
      - ansible
      - python-pip
      - nodejs-legacy
    jenkins_key_url: "https://pkg.jenkins.io/debian/jenkins.io.key"
    jenkins_repository: "deb http://pkg.jenkins.io/debian-stable binary/"
    jenkins_cli_jar: "http://localhost:8080/jnlpJars/jenkins-cli.jar" 
    build_job_checkboxio: "checkboxio"
    checkboxio_config_xml: "/tmp/checkboxio_config.xml"
    jenkins_home : /var/lib/jenkins/init.groovy.d
    itrust_config_xml: "/tmp/itrust_config.xml"
    build_job_itrust: "iTrust"
    ansible_repository: "ppa:ansible/ansible"

  vars_prompt:
    - name: github_username
      prompt: "Enter your NCSU github username"
      private: no
    - name: github_password
      prompt: "Enter your NCSU github password"
      private: yes
      confirm: yes
      
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
    
    - name: gather_facts
      setup:
      
    - name: Add Java8 repository
      apt_repository: repo={{ java8_repository }} state=present

    - name: Add Ansible repository
      apt_repository: repo={{ ansible_repository }} state=present      
    
    - name: Install all basic utilities- git and java
      apt: pkg="{{ item }}" state=present update_cache=yes
      with_items: "{{ utilities }}"
      
    - name: Add the key for Jenkins
      apt_key: url={{ jenkins_key_url }} state=present
      
    - name: Add Jenkins to /etc/apt/sources.list
      apt_repository: repo={{ jenkins_repository }} state=present
      
    - name: Install jenkins
      apt: pkg="jenkins" state=present update_cache=yes

    - name : Wait for jenkins service to be up
      wait_for:
       port: 8080
       delay: 45   
  
    - name: Turn off Jenkins setup wizard
      lineinfile: dest=/etc/default/jenkins regexp='^JAVA_ARGS=' line='JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

    - name : Disable security
      replace: 
        dest: /var/lib/jenkins/config.xml
        regexp: " <useSecurity>true</useSecurity>"
        replace: " <useSecurity>false</useSecurity>"

    - name : Restart Jenkins service
      service: 
       name: jenkins
       state: restarted  
       
    - name : Wait for jenkins service to be up
      wait_for:
       port: 8080
       delay: 45        

    - name: Add jenkins user to sudoer
      user: name=jenkins group=sudo groups="jenkins" state=present
      
    - name: Add line to /etc/sudoers
      lineinfile:
        dest: "/etc/sudoers"
        insertafter: EOF
        line: "jenkins ALL= NOPASSWD: ALL"
        state: present
     
    - name: Download Jenkins Cli Jar
      get_url: 
       url: "{{ jenkins_cli_jar }}"
       dest: /tmp
       
    - name: Install Jenkins plugins for Maven and Git 
      command: java -jar /tmp/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }}
      with_items:
       - maven-plugin
       - github
       - postbuild-task
       - jacoco
       - log-parser
       
    - name : Restart Jenkins service
      service: 
       name: jenkins
       state: restarted    
       
    - name : Wait for jenkins service to be up
      wait_for:
       port: 8080
       delay: 45

    - name: Create directory for groovy file
      file: 
       path: "{{ jenkins_home }}"
       state: directory
       owner: jenkins
       group: jenkins
       mode: 0775
       
    - name: Copy groovy file 
      copy:
       src: "/home/vagrant/DevOps_MileStone2/create-credentials.groovy"
       dest: "{{ jenkins_home }}/create-credentials.groovy"
       owner: jenkins
       group: jenkins
       mode: 0664
       
    - name: Add github credentials to create-credentials.groovy file
      lineinfile:
        dest: "{{ jenkins_home }}/create-credentials.groovy"
        insertafter: EOF
        line: "addPassword('{{ github_username }}', '{{ github_password }}')"
        state: present

    - name : Restart Jenkins service
      service: 
       name: jenkins
       state: restarted  
       
    - name : Wait for jenkins service to be up
      wait_for:
       port: 8080
       delay: 45        

    - name: Install boto and boto3
      pip:
        name: "{{ item }}"
      with_items:
        - boto
        - boto3
        
    - name: Disable strict host key checking
      lineinfile: dest=/etc/ssh/ssh_config line='    StrictHostKeyChecking no' insertafter=EOF state=present

    - name: Set up Checkboxio and its dependencies
      include_tasks: setup_checkbox.yml

    - name: Set up ITrust and its dependencies
      include_tasks: setup_itrust.yml


     
               
